### ISSUE TITLE
Refreshing user list page error.

### ISSUE THREAD

**Issue by Andrew-devweb** [FriendsOfFlarum/user-directory#50]
Hi! I noticed that whenever i refresh (F5) the user list page, I get an error. I'm not sure if it's missconfiguration of my flarum install but I wanted to send the error log anyway. 
The forum is currently in debug mode.

InvalidArgumentException
No hint path defined for [fof.user-directory].

![Immagine](https://user-images.githubusercontent.com/74706350/99642973-6d072d00-2a4c-11eb-88b2-34c92f75911e.png)

```
[2020-11-18 11:21:53] flarum.ERROR: InvalidArgumentException: No hint path defined for [fof.user-directory]. in /var/www/forum/vendor/illuminate/view/FileViewFinder.php:112
Stack trace:
#0 /var/www/forum/vendor/illuminate/view/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments()
#1 /var/www/forum/vendor/illuminate/view/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView()
#2 /var/www/forum/vendor/illuminate/view/Factory.php(131): Illuminate\View\FileViewFinder->find()
#3 /var/www/forum/vendor/fof/user-directory/src/Content/UserDirectory.php(75): Illuminate\View\Factory->make()
#4 /var/www/forum/vendor/flarum/core/src/Frontend/Frontend.php(63): FoF\UserDirectory\Content\UserDirectory->__invoke()
#5 /var/www/forum/vendor/flarum/core/src/Frontend/Frontend.php(55): Flarum\Frontend\Frontend->populate()
#6 /var/www/forum/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#7 /var/www/forum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Frontend\Controller->handle()
#8 /var/www/forum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#9 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#10 /var/www/forum/vendor/fof/ban-ips/src/Middleware/RegisterMiddleware.php(93): Laminas\Stratigility\Next->handle()
#11 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): FoF\BanIPs\Middleware\RegisterMiddleware->process()
#12 /var/www/forum/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#13 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#14 /var/www/forum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#15 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#16 /var/www/forum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(37): Laminas\Stratigility\Next->handle()
#17 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#18 /var/www/forum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#19 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#20 /var/www/forum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#21 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#22 /var/www/forum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#23 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#24 /var/www/forum/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#25 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CollectGarbage->process()
#26 /var/www/forum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#27 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#28 /var/www/forum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#29 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#30 /var/www/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#31 /var/www/forum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#32 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#33 /var/www/forum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#34 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#35 /var/www/forum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#36 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#37 /var/www/forum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#38 /var/www/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#39 /var/www/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#40 /var/www/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#41 /var/www/forum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#42 /var/www/forum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#43 /var/www/forum/public/index.php(26): Flarum\Http\Server->listen()
#44 {main}
```

**Comment by clarkwinkelmann** [comment]
This is a known issue, probably caused by the `fof/filter` extension https://github.com/FriendsOfFlarum/filter/issues/14

You can remove `fof/filter` or disable and re-enable it to work around the issue.

If you don't have `fof/filter` installed, can you share the output of `php flarum info` in the Flarum directory?

**Comment by Andrew-devweb** [comment]
Yep, it was fof/filter causing the issue. Thank you very much.
